// <auto-generated />
namespace EEP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nytakoe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nytakoe));
        
        string IMigrationMetadata.Id
        {
            get { return "201811182140556_ny takoe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
